version: "3"

networks:
  eduspace:
    external: true

services:
  eduspace-back:
    build: ../sun-house-back
    image: atomico592/eduspace:back
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - public_images:/src/app/public
  nginx:
    container_name: nginx
    image: nginx:1.18-alpine
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx-proxy/configs/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/configs/nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/configs/nginx/html:/usr/share/nginx/html
      - ./nginx-proxy/configs/nginx/certs:/etc/nginx/certs:ro
    restart: always
    networks:
      - eduspace
  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx-proxy/configs/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/configs/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/configs/nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/configs/nginx/html:/usr/share/nginx/html
      - ./nginx-proxy/configs/nginx/certs:/etc/nginx/certs:ro
    logging:
      driver: syslog
    restart: unless-stopped
    networks:
      - eduspace
    depends_on:
      - nginx

  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx
    volumes:
      - ./nginx-proxy/configs/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-proxy/configs/nginx/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/configs/nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/configs/nginx/html:/usr/share/nginx/html
    logging:
      driver: syslog
    restart: unless-stopped
    networks:
      - eduspace
    depends_on:
      - nginx-gen

  eduspace-front:
    build:
      context: ../SunHouseProjectFrontend
      args:
        api_url: "http://backend:8000"
    container_name: frontend
    restart: always
    image: atomico592/eduspace:front
    ports:
      - "81:81"
    expose:
      - "81"
    logging:
      driver: syslog
    networks:
      - eduspace

volumes:
  public_images:
  mongo_data: